### ISSUE TITLE
PyPlConv Error: no PyPlConv var known as '_version_' exists.

### ISSUE THREAD

**Issue by AlexModrono** [TehAlex11/PyPlConv#1]
I'm using OS X High Sierra 10.13.2 and I'm using **PyPlConv v1.0.0**. When converting a file to `**.crck**` I find the following error:
```python
PyPlConv Error: no PyPlConv var known as '_version_' exists.
File: PyPlConv.e
Line: 23
Code: obtain(_version_; os_process[0]);
```
The problem seems to be in a variable that isn't declared, but I cannot modify the code because PyPlConv.e is uploaded into PyPlConv server, so the only one who can change it is '**TehAlex11**'.

**Comment by TehAlex11** [comment]
This error occur only in version 1.0.0-pre_alpha, which was uploaded only to [Alex Modroño's PyPlConv Post](www.alejandromodroño.com/PyPlConv). If you downloaded it from there, you may have this error. To fix this, just go to releases and you'll find the **PyPlConv v1.0.0 Download**. You can replace all the code by running `cais rplace [path] -w ~[path2]` in terminal. Change [path] with the path PyPlConv with the problem is located, and [path2] with the path in which PyPlConv 1.0.0 download is located.

Hope this helps you

**Comment by AlexModrono** [comment]
Yes, I did everything you told and I suppose now it works. It doesn't show the error, but when I run the file I have another error. This is the code:

CAIS++ File code:
```CAIS++
#use <caispp>
use "PyPlConv.e"
use "PyPlConv.cai"
use "PyPlConv3.cai"

dfc main(sys_args[0]) {
    see if {
        PyPlConv::_version_ iscmp PyPlConv_version_requirements /# This is the line which gives error.
    }
}
```

The code is much bigger, but the only line which gives error is that.

The Python code seems to be fine, the terminal shows the following error:
``` python
PyPlConv Error: PyPlConv.args[3] found an exception (No PyPlConv.args found).
CAIS++ Error: CAIS++ Code seems to be interrupted.
File: PyPlConvTest1
Line: 8
Code: PyPlConv::_version_ iscmp PyPlConv_version_requirements
```
So I suppose this is a PyPlConv error because the Python code is correct.

**Comment by TehAlex11** [comment]
That happens when a CAIS++ file doesn't have permissions or what you are trying to modify doesn't exist. As I see, your code is trying to read or to modify something, to do that we need `sys_args[]` at level 3, to read or modify something, and when it doesn't have permissions or the file doesn't exist, `sys_args[]` is set to 0. Try running `chmod +x [path]` in terminal. Change [path] with the path in which your CAIS++ file is located, NOT the python one.

**Comment by AlexModrono** [comment]
Oh, thanks, now it works successfully. The script read a file and stored that value in variables, it worked like a pseudo-interpreter. I wrote the command and now it seems to do not give error.
Thanks!

**Comment by TehAlex11** [comment]
Ok, hope this solves your problem.

**Solved**
